openapi: 3.0.0
info:
  title: Loom API (public beta)
  description: 'This is the documentation of the Connect Print Loom API Endpoints.'
  version: 1.0.0
servers:
  - url: https://loom.zaikami.cloud/api/v1/

tags:
  - name: Events

paths:
  /events:
    post:
      tags:
        - Events
      description: >
        Fires a new event with the given arguments.
      parameters:
        - in: query
          name: event[id]
          required: true
          description: Must be an unique UUID for each fired event
          schema:
            type: string
            format: uuid
            example: d6308910-f5ae-58c0-aba7-d099947845c6
        - in: query
          name: event[timestamp]
          required: true
          description: ISO8601 timestamp of the event
          schema:
            type: date-time
            example: 2019-11-18T14:06:40.421Z
        - in: query
          name: event[name]
          required: true
          description: With <app_name>.<event_name> from the Directory
          schema:
            type: string
            example: accounting.invoice_paid
        - in: query
          name: event[subject]
          required: true
          description: Type and id of the subject that triggered the event, see [Guide](/guide/loom/posting-events.html) for further requirements
          schema:
            type: string
            example: 'Org/2b271d51-e447-4a16-810f-5abdc596700a'
            pattern: '/(Org|Per)\/[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-\b[0-9a-f]{12}/'
        - in: query
          name: event[version]
          required: true
          description: Version of the payload structure and format
          schema:
            type: integer
            example: 1
        - in: query
          name: event[payload]
          description: The payload must be a hash and may not exceed 256 bytes, see [Guide](/guide/loom/posting-events.html#payload-requirements) for further requirements
          schema:
            type: object
            additionalProperties: {}
            example: { "invoice_number": 1234 }
        - in: query
          name: event[link]
          description: An URL providing further information about this event
          schema:
            type: string
            format: uri
            example: https://accounting.zaikami.cloud/api/v1/payments/1234
      security:
        - basicAuth: []
      responses:
        '201':
          description: Created
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrors'
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity (Validation error during creation)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrors'
        '429':
          description: Too Many Requests, API rate limit exceeded

    get:
      tags:
        - Events
      description: >
        Returns all subscribed events matching the filter. Please note that the response is limited to events to which the app is subscribed in the Directory.
      parameters:
        - in: path
          name: filter[name]
          description: Filter events by name
          schema:
            type: string
            example: accounting.invoice_paid
        - in: path
          name: filter[from]
          description: Filter events by timestamp
          schema:
            type: date-time
            example: 2019-11-01T00:00:00.000Z
        - in: path
          name: filter[to]
          description: Filter events by timestamp
          schema:
            type: date-time
            example: 2019-11-01T23:59:59.999Z
        - in: path
          name: page
          description: Events are paginated to 100 events per default
          schema:
            type: integer
            example: 1
      security:
        - basicAuth: []
      responses:
        '200':
          description: Returns all events that matches the query
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
          headers:
            X-Total-Count:
              description: Number of events matching the filter
              schema:
                type: integer
            Link:
              description: RFC5988 pagination and navigation link
              schema:
                type: string
        '401':
          description: Unauthorized
        '422':
          description: Unprocessable Entity (Invalid fiter)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FilterErrors'
        '429':
          description: Too Many Requests, API rate limit exceeded

components:
  schemas:
    uuid:
      type: string
      format: uuid

    Event:
      required:
        - id
        - timestamp
        - name
        - version
        - payload
        - link
        - received_at
      properties:
        id:
          allOf:
            - $ref: '#/components/schemas/uuid'
            - example: '62abcc92-e17e-4db0-b78e-13369251474b'
        name:
          type: string
          example: accounting.invoice_paid
        timestamp:
          type: string
          format: date-time
          example: 2019-11-28T09:31:45.764Z
        subject:
          type: string
          example: 'Org/2b271d51-e447-4a16-810f-5abdc596700a'
        version:
          type: string
          example: '1.2'
        payload:
          type: object
          description: "A hashmap with keys in lowercase snake_case. Format and structure is defined by the app that fires an event. example: { invoice_number: 1234 }"
          additionalProperties: {}
          example:
            invoice_number: 1234
        link:
          type: string
          nullable: true
          format: uri
          example: https://accounting.zaikami.cloud/api/v1/payments/1234
        received_at:
          type: string
          format: date-time
          example: 2019-11-28T09:31:45.764Z

    FilterErrors:
      required:
        - errors
      type: object
      properties:
        errors:
          type: object
          example:
            from:
              - invalid date-time
          additionalProperties:
            type: array
            items:
              type: string

    ValidationErrors:
      required:
        - errors
      type: object
      properties:
        errors:
          type: object
          example:
            name:
              - can't be blank
          additionalProperties:
            type: array
            items:
              type: string

  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
